# https://gohugo.io/getting-started/configuration/
baseUrl: "https://bravebright.github.io/"
hasCJKLanguage: true # https://gohugo.io/getting-started/configuration/#hascjklanguage
theme: "tale" # https://github.com/EmielH/tale-hugo
title: "YONEDA Yūki"
